name: Deploy job

on:
  pull_request:
    branches:
      - '_prod/**'
  merge_group:
    branches:
      - '_prod/**'

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'merge_group' }}
    steps:
      - name: Sleep & fail
        run: |
          sleep 300
          exit 1
